Start debugging broken CI reporting in Github comments. Try posting a simlpe comment without running the rest of the CI.

diff --git a/.github/workflows/model_ci.yml b/.github/workflows/model_ci.yml
--- a/.github/workflows/model_ci.yml
+++ b/.github/workflows/model_ci.yml
@@ -21,36 +21,40 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
+    # - uses: actions/checkout@v2
 
-    - name: Set up Python 3.7
-      uses: actions/setup-python@v1
-      with:
-        python-version: 3.7
+    # - name: Set up Python 3.7
+    #   uses: actions/setup-python@v1
+    #   with:
+    #     python-version: 3.7
 
-    - name: Install dependencies
+    # - name: Install dependencies
+    #   run: |
+    #     python -m pip install --upgrade "pip<20"
+    #     pip install -r requirements.txt
+
+    # - name: Check stories are consistent
+    #   run: |
+    #     rasa data validate stories --max-history 5 --fail-on-warning
+
+    # - name: Train model
+    #   run: |
+    #     rasa train
+
+    # - name: Run Through Test Stories
+    #   run: |
+    #     rasa test core --stories test_stories/stories.yaml --fail-on-prediction-errors
+
+    # - name: Cross-validate NLU model
+    #   id: cvnlu
+    #   if: github.event_name == 'pull_request'
+    #   run: |
+    #     rasa test nlu -f 2 --cross-validation
+    #     python format_results.py
+
+    - name: Generate dummy results file
       run: |
-        python -m pip install --upgrade "pip<20"
-        pip install -r requirements.txt
-
-    - name: Check stories are consistent
-      run: |
-        rasa data validate stories --max-history 5 --fail-on-warning
-
-    - name: Train model
-      run: |
-        rasa train
-
-    - name: Run Through Test Stories
-      run: |
-        rasa test core --stories test_stories/stories.yaml --fail-on-prediction-errors
-
-    - name: Cross-validate NLU model
-      id: cvnlu
-      if: github.event_name == 'pull_request'
-      run: |
-        rasa test nlu -f 2 --cross-validation
-        python format_results.py
+        echo "Hi there" > results.md
 
     - name: Upload Cross Validation Results
       if: github.event_name == 'pull_request'
@@ -73,165 +77,165 @@ jobs:
       with:
         msg: results.md
 
-  build-images:
-    name: Build and Push Images
-    runs-on: ubuntu-latest
-    env:
-      IS_PUSH_EVENT: ${{ github.event_name == 'push' }}
+  # build-images:
+  #   name: Build and Push Images
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     IS_PUSH_EVENT: ${{ github.event_name == 'push' }}
 
-    steps:
-    - uses: actions/checkout@v2
+  #   steps:
+  #   - uses: actions/checkout@v2
 
-    - name: Set image tag
-      run: |
-        if [[ $IS_PUSH_EVENT == "false" ]]
-        then
-          IMAGE_TAG=${{ github.head_ref }}
-        else
-          IMAGE_TAG=$(basename ${{ github.ref }})
-        fi
+  #   - name: Set image tag
+  #     run: |
+  #       if [[ $IS_PUSH_EVENT == "false" ]]
+  #       then
+  #         IMAGE_TAG=${{ github.head_ref }}
+  #       else
+  #         IMAGE_TAG=$(basename ${{ github.ref }})
+  #       fi
 
-        echo "IMAGE_TAG=${IMAGE_TAG}-${{ github.sha }}" >> $GITHUB_ENV
+  #       echo "IMAGE_TAG=${IMAGE_TAG}-${{ github.sha }}" >> $GITHUB_ENV
 
-    # Setup gcloud CLI
-    - uses: google-github-actions/setup-gcloud@v0.2.1
-      name: Google Auth
-      with:
-        service_account_key: ${{ secrets.GKE_SA_KEY }}
-        project_id: ${{ secrets.GKE_PROJECT }}
+  #   # Setup gcloud CLI
+  #   - uses: google-github-actions/setup-gcloud@v0.2.1
+  #     name: Google Auth
+  #     with:
+  #       service_account_key: ${{ secrets.GKE_SA_KEY }}
+  #       project_id: ${{ secrets.GKE_PROJECT }}
 
-    # Configure docker to use the gcloud command-line tool as a credential helper
-    - run: |-
-        gcloud --quiet auth configure-docker
+  #   # Configure docker to use the gcloud command-line tool as a credential helper
+  #   - run: |-
+  #       gcloud --quiet auth configure-docker
 
-    - name: Build and push the Docker image
-      run: |
-        # Read and export variables from .env file
-        set -o allexport; source .env; set +o allexport
-        docker build . \
-          --build-arg RASA_SDK_IMAGE=rasa/rasa-sdk:${RASA_SDK_VERSION} \
-          --tag gcr.io/${{ secrets.GKE_PROJECT }}/carbon-bot-actions:$IMAGE_TAG
-        docker push gcr.io/${{ secrets.GKE_PROJECT }}/carbon-bot-actions:$IMAGE_TAG
+  #   - name: Build and push the Docker image
+  #     run: |
+  #       # Read and export variables from .env file
+  #       set -o allexport; source .env; set +o allexport
+  #       docker build . \
+  #         --build-arg RASA_SDK_IMAGE=rasa/rasa-sdk:${RASA_SDK_VERSION} \
+  #         --tag gcr.io/${{ secrets.GKE_PROJECT }}/carbon-bot-actions:$IMAGE_TAG
+  #       docker push gcr.io/${{ secrets.GKE_PROJECT }}/carbon-bot-actions:$IMAGE_TAG
 
-  deploy-to-cluster:
-    name: Re-deploy the cluster with the latest action server
-    runs-on: ubuntu-latest
+  # deploy-to-cluster:
+  #   name: Re-deploy the cluster with the latest action server
+  #   runs-on: ubuntu-latest
 
-    needs:
-    - build-images
+  #   needs:
+  #   - build-images
 
-    if: github.event_name == 'push' && (startsWith(github.event.ref, 'refs/tags') || github.ref == 'refs/heads/master')
+  #   if: github.event_name == 'push' && (startsWith(github.event.ref, 'refs/tags') || github.ref == 'refs/heads/master')
 
-    steps:
-    # Checkout repository because we need the content of the `.env` file later
-    - uses: actions/checkout@v2
+  #   steps:
+  #   # Checkout repository because we need the content of the `.env` file later
+  #   - uses: actions/checkout@v2
 
-    - name: Set image tag
-      env:
-        IS_PUSH_EVENT: ${{ github.event_name == 'push' }}
-      run: |
-        if [[ $IS_PUSH_EVENT == "false" ]]
-        then
-          IMAGE_TAG=${{ github.head_ref }}
-        else
-          IMAGE_TAG=$(basename ${{ github.ref }})
-        fi
+  #   - name: Set image tag
+  #     env:
+  #       IS_PUSH_EVENT: ${{ github.event_name == 'push' }}
+  #     run: |
+  #       if [[ $IS_PUSH_EVENT == "false" ]]
+  #       then
+  #         IMAGE_TAG=${{ github.head_ref }}
+  #       else
+  #         IMAGE_TAG=$(basename ${{ github.ref }})
+  #       fi
 
-        echo "IMAGE_TAG=${IMAGE_TAG}-${{ github.sha }}" >> $GITHUB_ENV
+  #       echo "IMAGE_TAG=${IMAGE_TAG}-${{ github.sha }}" >> $GITHUB_ENV
 
-    # Setup gcloud CLI
-    - uses: google-github-actions/setup-gcloud@v0.2.1
-      name: Google Auth
-      with:
-        service_account_key: ${{ secrets.GKE_SA_KEY }}
-        project_id: ${{ secrets.GKE_PROJECT }}
+  #   # Setup gcloud CLI
+  #   - uses: google-github-actions/setup-gcloud@v0.2.1
+  #     name: Google Auth
+  #     with:
+  #       service_account_key: ${{ secrets.GKE_SA_KEY }}
+  #       project_id: ${{ secrets.GKE_PROJECT }}
 
-    # Configure docker to use the gcloud command-line tool as a credential helper
-    - run: |-
-        gcloud --quiet auth configure-docker
+  #   # Configure docker to use the gcloud command-line tool as a credential helper
+  #   - run: |-
+  #       gcloud --quiet auth configure-docker
 
-    # Get the GKE credentials so we can deploy to the cluster
-    - uses: google-github-actions/get-gke-credentials@v0.2.1
-      with:
-        cluster_name: ${{ secrets.GKE_CLUSTER }}
-        location: ${{ secrets.GKE_ZONE }}
-        credentials: ${{ secrets.GKE_SA_KEY }}
+  #   # Get the GKE credentials so we can deploy to the cluster
+  #   - uses: google-github-actions/get-gke-credentials@v0.2.1
+  #     with:
+  #       cluster_name: ${{ secrets.GKE_CLUSTER }}
+  #       location: ${{ secrets.GKE_ZONE }}
+  #       credentials: ${{ secrets.GKE_SA_KEY }}
 
-    - name: Install Helm and helmfile ⛑
-      run: |
-        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
-        chmod 700 get_helm.sh
-        ./get_helm.sh
-        sudo curl -fsSL https://github.com/roboll/helmfile/releases/download/v0.138.7/helmfile_linux_amd64 --output /usr/local/bin/helmfile
-        sudo chmod +x /usr/local/bin/helmfile
+  #   - name: Install Helm and helmfile ⛑
+  #     run: |
+  #       curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
+  #       chmod 700 get_helm.sh
+  #       ./get_helm.sh
+  #       sudo curl -fsSL https://github.com/roboll/helmfile/releases/download/v0.138.7/helmfile_linux_amd64 --output /usr/local/bin/helmfile
+  #       sudo chmod +x /usr/local/bin/helmfile
 
-    - name: Install Chart
-      env:
-        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
-        RASA_TOKEN: ${{ secrets.RASA_TOKEN }}
-        RASA_X_TOKEN: ${{ secrets.RASA_X_TOKEN }}
-        JWT_SECRET: ${{ secrets.JWT_SECRET }}
-        PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
-        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
-        RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
-        RASA_X_ADMIN_PASSWORD: ${{ secrets.RASA_X_ADMIN_PASSWORD }}
-        GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
+  #   - name: Install Chart
+  #     env:
+  #       DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+  #       RASA_TOKEN: ${{ secrets.RASA_TOKEN }}
+  #       RASA_X_TOKEN: ${{ secrets.RASA_X_TOKEN }}
+  #       JWT_SECRET: ${{ secrets.JWT_SECRET }}
+  #       PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
+  #       REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
+  #       RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
+  #       RASA_X_ADMIN_PASSWORD: ${{ secrets.RASA_X_ADMIN_PASSWORD }}
+  #       GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
 
-      run: |
-        # Install helm v3
-        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
+  #     run: |
+  #       # Install helm v3
+  #       curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
 
-        # Read and export variables from .env file
-        set -o allexport; source .env; set +o allexport
+  #       # Read and export variables from .env file
+  #       set -o allexport; source .env; set +o allexport
 
-        kubectl create ns ${NAMESPACE} || true
-        cd .github/deployments; helmfile sync
+  #       kubectl create ns ${NAMESPACE} || true
+  #       cd .github/deployments; helmfile sync
 
-        cat <<EOF | kubectl apply --namespace ${NAMESPACE} -f  -
-        apiVersion: networking.gke.io/v1beta1
-        kind: ManagedCertificate
-        metadata:
-          generation: 1
-          name: rasa-bots-certificate
-        spec:
-          domains:
-          - ${{ env.DOMAIN }}
-        EOF
+  #       cat <<EOF | kubectl apply --namespace ${NAMESPACE} -f  -
+  #       apiVersion: networking.gke.io/v1beta1
+  #       kind: ManagedCertificate
+  #       metadata:
+  #         generation: 1
+  #         name: rasa-bots-certificate
+  #       spec:
+  #         domains:
+  #         - ${{ env.DOMAIN }}
+  #       EOF
 
-  upload-model:
-    name: Upload the trained model to Rasa X
-    needs:
-    - deploy-to-cluster
-    - build-model
-    env:
-      MODEL_DIRECTORY: "models"
+  # upload-model:
+  #   name: Upload the trained model to Rasa X
+  #   needs:
+  #   - deploy-to-cluster
+  #   - build-model
+  #   env:
+  #     MODEL_DIRECTORY: "models"
 
-    if: github.event_name == 'push' && (startsWith(github.event.ref, 'refs/tags') || github.ref == 'refs/heads/master')
-    runs-on: ubuntu-latest
+  #   if: github.event_name == 'push' && (startsWith(github.event.ref, 'refs/tags') || github.ref == 'refs/heads/master')
+  #   runs-on: ubuntu-latest
 
-    steps:
-    - name: Download Model
-      uses: actions/download-artifact@v2
-      with:
-        name: model
-        path: ${{ env.MODEL_DIRECTORY }}
+  #   steps:
+  #   - name: Download Model
+  #     uses: actions/download-artifact@v2
+  #     with:
+  #       name: model
+  #       path: ${{ env.MODEL_DIRECTORY }}
 
-    - name: Get path to model
-      run: |
-        ls -R
-        echo "MODELNAME=${{ env.MODEL_DIRECTORY }}/$(ls ${{ env.MODEL_DIRECTORY }})" >> $GITHUB_ENV
+  #   - name: Get path to model
+  #     run: |
+  #       ls -R
+  #       echo "MODELNAME=${{ env.MODEL_DIRECTORY }}/$(ls ${{ env.MODEL_DIRECTORY }})" >> $GITHUB_ENV
 
-    - name: Upload Model to Rasa
-      run: |
-        # Get token
-        RASA_X_TOKEN=$(curl -s --header "Content-Type: application/json" \
-          --request POST \
-          --data "{\"username\":\"${RASA_X_USERNAME}\",\"password\":\"${RASA_X_PASSWORD}\"}" \
-          https://${{ env.DOMAIN }}/api/auth | jq -r .access_token)
+  #   - name: Upload Model to Rasa
+  #     run: |
+  #       # Get token
+  #       RASA_X_TOKEN=$(curl -s --header "Content-Type: application/json" \
+  #         --request POST \
+  #         --data "{\"username\":\"${RASA_X_USERNAME}\",\"password\":\"${RASA_X_PASSWORD}\"}" \
+  #         https://${{ env.DOMAIN }}/api/auth | jq -r .access_token)
 
-        # Upload model
-        curl -k --fail -H "Authorization: Bearer ${RASA_X_TOKEN}" -F "model=@${MODELNAME}" https://${{ env.DOMAIN }}/api/projects/default/models
-        # ensure model is ready and tag as production
-        sleep 5
-        export MODEL=$(basename ${MODELNAME} .tar.gz)
-        curl --fail -XPUT -H "Authorization: Bearer ${RASA_X_TOKEN}" https://${{ env.DOMAIN }}/api/projects/default/models/${MODEL}/tags/production
+  #       # Upload model
+  #       curl -k --fail -H "Authorization: Bearer ${RASA_X_TOKEN}" -F "model=@${MODELNAME}" https://${{ env.DOMAIN }}/api/projects/default/models
+  #       # ensure model is ready and tag as production
+  #       sleep 5
+  #       export MODEL=$(basename ${MODELNAME} .tar.gz)
+  #       curl --fail -XPUT -H "Authorization: Bearer ${RASA_X_TOKEN}" https://${{ env.DOMAIN }}/api/projects/default/models/${MODEL}/tags/production
